services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/var/www/html
      - ./php/src:/var/www/php
      - ./socket:/var/run
  php:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./php/src:/var/www/php
      - ./php/php-fpm.d/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/php-fpm.d/unix-socket.conf:/usr/local/etc/php-fpm.d/zzz-unix-socket.conf
      - ./socket:/var/run
    ports:
      - "9000"
  redis:
    image: redis:alpine3.12
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
